config/routes.rb
Rails.application.routes.draw do
  get "/", to: "users#index", as: "home" #LANDING PAGE
  get "/users", to: "users#index", as: "users" #users_path needed for form_for
  post "/users", to: "users#create"
  get "/register", to: "users#new", as: "register" #REGISTRATION
  post "/users/save_data", to: "users#save_data", as: "save"

  get "/sessions", to: "sessions#index", as: "sessions"
  get "/login", to: "sessions#new"#, as: "login" #LOGIN PAGE
  post "/login", to: "sessions#create"#, as: "login"
  get "/unlock", to: "sessions#unlock", as: "unlock" #UNLOCK & DECRYPT PAGE
  get "/logout", to: "sessions#destroy", as: "logout" #GET or DELETE request?
  get "/dashboard", to: "sessions#dashboard", as: "dashboard"
  get "/sessions/api", to: "sessions#api" #fetches logged-in user's "data" field to then decrypt and show


  # resources :users
  # resources :sessions

  root "users#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # include Encryption
  # attr_encryptor :email, key: ENV["EMAIL_ENC_ATTR"]#, algorithm: 'aes-256-gcm', mode: :per_attribute_iv, encode: true, encode_iv: true, encode_salt: true
  has_secure_password

  validates :email, presence: true, uniqueness: true, length: {:minimum => 5, :maximum => 99}, format: { with: /.+@.+\..+/i } #all I check for is the @ and a dot
  # validates :password, length: {minimum: 8}
  before_create { generate_token(:remember_token) }

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_token, User.token(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_token.nil?
    BCrypt::Password.new(remember_token).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_token, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def current_user
    @current_user ||= User.find_by(remember_token: cookies[:remember_token]) if cookies[:remember_token]
  end
  helper_method :current_user

  def authorize
    current_user
    redirect_to login_url, alter: "You do not have access" if @current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authorize, except: [:new, :create, :destroy]

  def new #sends to Login page
  end

  def unlock #sends to Unlock page
  end

  def create #creates new session if user & password are legit
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      if params[:session][:remember_me]
        cookies.permanent[:remember_token] = user.remember_token
      else
        cookies[:remember_token] = user.remember_token
      end
      redirect_to unlock_path
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def dashboard #sends to dashboard
    @data = current_user.data
  end

  def api #used to get logged-in user's "data" field in the database
    apidata = current_user.data
    render text: apidata
  end

  def destroy
    log_out if logged_in?
    cookies.delete(:remember_token)
    reset_session
    redirect_to root_url, notice: "Logged out. Please close the browser window now"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:index, :new, :create]

  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to '/dashboard', notice: "Upload loan data to get started."
    else
      render "new"
    end
  end

  def save_data
    encoutputstring = params.first[0]
    current_user.data = encoutputstring
    current_user.save
    flash.clear
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
   forget(current_user)
   session.delete(:user_id)
   @current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Fincript</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application'%>
    </head>
    <nav class="navbar-default navbar">
        <div class="container-fluid">
            <div class="navbar-collapse">
                <ul class="nav nav-pills">
                    <li class="navbar-text" role="presentation"><%= link_to "Home", home_path %></li>
                    <% if current_user %>
                    <li class="navbar-text" role="presentation"><%= link_to "Unlock", unlock_path %></li>
                    <li class="navbar-text" role="presentation"><%= link_to "Dashboard", dashboard_path %></li>
                    <li class="navbar-text" role="presentation" id="logout"><%= link_to "Log Out", logout_path %></li>
                    <!-- controller action does not use "current" parameter, but you have to pass something -->
                    <p class="navbar-text" id="WelcomeUser">Welcome:
                        <span id="welcomeUserName"><%= current_user.email %></span>
                    </p>
                <% else %>
                    <li class="navbar-text" role="presentation"><%= link_to "Sign Up", register_path %></li>
                    <li class="navbar-text" role="presentation"><%= link_to "Log In", login_path %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
    <div>
        <% if flash[:notice] %>
        <div class="notice"><%= flash[:notice] %></div>
        <% end %>
    </div>
    <body class="<%= controller_name %> <%= action_name %>">
        <%= yield %>
    </body>
</html>

app/views/users/index.html.erb
<div class="overlay">
    <div id="makeHeaderSpace"></div>
    <div class="container-fluid" id="appOverview">
        <div class="row">
            <div class="col-md-3 col-md-offset-2 previewTextParent">
                <div class="landingPageMotivation"> <span class="landingPageSVG"><%=image_tag("calculator.svg", size: "50x50")%></span>
                      Average student loan holder will pay almost
                    <em>double</em>, due to interest.
                </div>
                <!-- <hr /> -->
                <div class="landingPageMotivation"><span class="landingPageSVG"><%=image_tag("locked.svg", size: "50x50")%></span>
                    Secure and <em>confidential</em>.
                </div>
                <!-- <hr /> -->
                <div class="landingPageMotivation"><span class="landingPageSVG"><%=image_tag("tool.svg", size: "50x50")%></span> Navigate your financial future.
                </div>
                <!-- <hr/> -->
            </div>
            <div class="col-md-6">
                <%=image_tag("screenshot1.png", size: "800x800", alt: "App Preview", class: "appPreviewImage img-responsive")%>
            </div>
        </div>
    </div>
    <div id=makeMiddleSpace></div>
    <div class="container-fluid" id="ZKexplanation">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div>
        We add an extra layer of security and confidentiality to your personal financial data. In addition to the standard best practices, we also have you encrypt your data before sending it to us to store. All of your data is encrypted before it ever leaves your computer. What this means is: we cannot access your data even if we wanted to. It is stored encrypted in the database.
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12"></div>
        </div>
        <div class="row" id="statssection">
            <div class="col-md-4">
                <span class="boxtitle text-center center-block">Student debt is widespread and burdensome</span>
                <div class="statbox center-block">
                    <ul class="debtlist">
                        <li>13.5% of Americans have student loan debt</li>
                        <li>Average monthly student loan payment $351</li>
                        <!--(for borrower aged 20 to 30 years):-->
                        <li>Student loan delinquency rate of 11.6%</li>
                    </ul>
                </div>
            </div>
            <div class="col-md-4" id="debtMapContainer">
                <%=image_tag("loandebtmap.png", size: "520x350", alt: "Student Loan Debt Donut Chart", class: "img-responsive img-rounded debtMapImage text-center center-block")%>
            </div>
            <div class="col-md-4">
                <span class="boxtitle text-center center-block">Americans are not financially healthy</span>
                <div class="statbox center-block">
                    <ul class="debtlist">
                        <li>1/3 Americans have NO retirement savings</li>
                        <li>80% of Americans do not have enough saved for retirement</li>
                        <li>Average U.S. household carries $15,675 in credit card debt</li>
                        <!-- and $27,865 in Auto loans-->
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <div class="calltoactionparent">
        <div class="calltoaction">
            Take charge of your finances by
            <em>optimizing</em>
            your debt paydown strategy
        </div>
    </div>
</div>

app/views/users/new.html.erb
<div>
    <div id="makeMarginSpace"></div>

    <div class="container">
        <div class="background">
            <div class="embed-submit-field">
                <%= form_for @user do |f| %>
                <% if @user.errors.any? %>
                <div class="error_messages">
                    <h2>Form is invalid</h2>
                    <ul>
                        <% @user.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                        <% end %>
                    </ul>
                </div>
                <% end %>

                <div class="field">
                    <span class="labeltag"><%= f.label :email %></span><br/>
                    <%= f.text_field :email, placeholder: "Email" %>
                </div>
                <div class="field">
                    <span class="labeltag"><%= f.label :password %></span><br/>
                    <%= f.password_field :password, placeholder: "Password" %>
                </div>
                <div class="field">
                    <span class="labeltag"><%= f.label :password_confirmation %></span><br/>
                    <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
                </div>
                <div class="actions btn submittagRegister"><%= f.submit "Sign Up" %></div>
                <% end %>

            </div>
        </div>
    </div>
</div>